stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch build/info.txt
        - echo "chasis" > info.txt
        - echo "Engine" >> info.txt
        - echo "infra"  >> info.txt
    artifacts:
        paths:
            - build/

test:
    stage: test
    script:
        - echo "Testing"
        - test -f "build/info.txt"
        - cd build
        - grep "chasis" info.txt
        - grep "Engine" info.txt
